name = "flight-scraper-browser"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ] # Required for Puppeteer

# Import HTML as string
[rules]
  [[rules.rule]]
    type = "Text"
    globs = ["**/*.html"]

# bind the browser capability
[browser]
binding = "MYBROWSER"
