name = "flight-scraper-browser"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

# browser binding
[browser]
binding = "MYBROWSER" 

# CORRECT RULES SYNTAX
[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true
